name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libssl1.0.0
        sudo apt-get install -y mysql-client
        sudo apt-get install -y libmysqlclient-dev
        sudo apt-get install -y libace-dev
        sudo apt-get install -y libreadline-dev
    - name: Verify MySQL connection from host
      run: |
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
    - name: Run CMAKE
      run: cmake -DSCRIPTS=1 -DTOOLS=1 -DSCRIPTS="dynamic" -DSERVERS=1 -DNOJEM=1 -DWITH_DYNAMIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
    - name: Run Make
      run: make -j 4
    - name: Run Make Install
      run: make install
    
